export { default as Dialog } from './Dialog'
export { default as Result } from './Result'
export { default as Form } from './Form'
export { default as FormSupplierRegister } from './FormSupplierRegister'
export { default as FormVote } from './FormVote'
export { default as ErrorDialog } from './ErrorDialog'
export { default as Loading } from './Loading'
